#!/bin/bash

PROGRAM=$0
PROGDIR=${PROGRAM%alarm}
CONFIGDIR=$PROGDIR

arg3=""

if [ "$2" = "" ] || [ "$4" != "" ]
	then echo "usage: alarm [hours] [minutes] | [hours] [minutes [config file]"
		 exit
fi

if [ "$3" != "" ]
	then arg3=$3
else
	arg3="$CONFIGDIR/config"
fi

exec $PROGDIR/alarm-bin $1 $2 $arg3

